# Site settings
title: Kai Zhang
email: kylerzhang11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kai Zhang's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  kkpattern

# Build settings
markdown: kramdown

kramdown:
  input: GFM
